config/routes.rb
Rails.application.routes.draw do

  resources :statuses

  resources :chairs

  resources :time_slots

  resources :derm_codes

  get 'officemenu/index'

  get 'officemenu/show'

  get 'welcome/index'

  resources :appointments

  resources :physicians

  resources :patients

  resources :admin

  resources :officemenu

  resources :derm_codes

   root 'welcome#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  belongs_to :physician
  belongs_to :patient
  belongs_to :derm_code
  belongs_to :time_slot
  belongs_to :chair
  belongs_to :status
end

app/models/chair.rb
class Chair < ActiveRecord::Base

  has_many :appointments
  belongs_to :time_slot, through: :appointment

end

app/models/derm_code.rb
class DermCode < ActiveRecord::Base

  has_many :appointments
  has_many :physicians, :through => :appointments
end

app/models/invoicing_tax_rate.rb
class InvoicingTaxRate < ActiveRecord::Base
  acts_as_tax_rate
end

app/models/office.rb
class Office < ActiveRecord::Base


end

app/models/patient.rb
class Patient < ActiveRecord::Base

  has_many :appointments
  has_many :physicians, :through => :appointments
end

app/models/physician.rb
class Physician < ActiveRecord::Base

  has_many :appointments
  has_many :patients, :through => :appointments
end

app/models/status.rb
class Status < ActiveRecord::Base

  has_many :appointments
end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base

  has_many :appointments
  has_many :chairs, through: :appointments
  end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table


  end
end

app/helpers/chairs_helper.rb
module ChairsHelper
end

app/helpers/derm_codes_helper.rb
module DermCodesHelper
end

app/helpers/officemenu_helper.rb
module OfficemenuHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<h1>Administration Menu</h1>
<h2></h2>
<p>
  <%= link_to 'Modify Physicians', physicians_path %>
  <%= link_to 'Modify Dermatology Codes', derm_codes_path %>
  <%= link_to 'Modify Time Slots', time_slots_path %>
  <%= link_to 'Completed Invoices', new_appointment_path %>
  <%= link_to 'Back', :back %>


  <!-- <%= link_to 'Appointments', appointments_path %>
  -->
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Indproject" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Home</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Appointments", "appointments"  %></li>
            <li><%= link_to "Office Menu", "officemenu"  %></li>
            <li><%= link_to "Admin Menu", "admin"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <!-- <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>

            </ul>
          </div></.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p></p>
        <p></p>
        <p></p>
        <p></p>
        <p>        </p>
        <p> Victor Mann 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>