config/routes.rb
Rails.application.routes.draw do

  resources :statuses

  resources :chairs

  resources :time_slots

  resources :derm_codes

  get 'officemenu/index'

  get 'officemenu/show'

  get 'welcome/index'

  resources :appointments

  resources :physicians

  resources :patients

  resources :admin

  resources :officemenu

  resources :derm_codes

   root 'welcome#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  belongs_to :physician
  belongs_to :patient
  belongs_to :derm_code
  belongs_to :time_slot
  belongs_to :chair
  belongs_to :status
end

app/models/chair.rb
class Chair < ActiveRecord::Base

  has_many :appointments
  belongs_to :time_slot, through: :appointment

end

app/models/derm_code.rb
class DermCode < ActiveRecord::Base

  has_many :appointments
  has_many :physicians, :through => :appointments
end

app/models/invoicing_line_item.rb
class InvoicingLineItem < ActiveRecord::Base
  acts_as_line_item

  belongs_to :ledger_item, class_name: 'InvoicingLedgerItem'
end

app/models/invoicing_tax_rate.rb
class InvoicingTaxRate < ActiveRecord::Base
  acts_as_tax_rate
end

app/models/office.rb
class Office < ActiveRecord::Base


end

app/models/patient.rb
class Patient < ActiveRecord::Base

  has_many :appointments
  has_many :physicians, :through => :appointments
end

app/models/physician.rb
class Physician < ActiveRecord::Base

  has_many :appointments
  has_many :patients, :through => :appointments
end

app/models/status.rb
class Status < ActiveRecord::Base

  has_many :appointments
end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base

  has_many :appointments
  has_many :chairs, through: :appointments
  end

app/controllers/time_slots_controller.rb
class TimeSlotsController < ApplicationController
  before_action :set_time_slot, only: [:show, :edit, :update, :destroy]

  # GET /time_slots
  # GET /time_slots.json
  def index
    @time_slots = TimeSlot.all
  end

  # GET /time_slots/1
  # GET /time_slots/1.json
  def show
  end

  # GET /time_slots/new
  def new
    @time_slot = TimeSlot.new
  end

  # GET /time_slots/1/edit
  def edit
  end

  # POST /time_slots
  # POST /time_slots.json
  def create
    @time_slot = TimeSlot.new(time_slot_params)

    respond_to do |format|
      if @time_slot.save
        format.html { redirect_to @time_slot, notice: 'Time slot was successfully created.' }
        format.json { render :show, status: :created, location: @time_slot }
      else
        format.html { render :new }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_slots/1
  # PATCH/PUT /time_slots/1.json
  def update
    respond_to do |format|
      if @time_slot.update(time_slot_params)
        format.html { redirect_to @time_slot, notice: 'Time slot was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_slot }
      else
        format.html { render :edit }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_slots/1
  # DELETE /time_slots/1.json
  def destroy
    @time_slot.destroy
    respond_to do |format|
      format.html { redirect_to time_slots_url, notice: 'Time slot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_slot
      @time_slot = TimeSlot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_slot_params
      params.require(:time_slot).permit(:start_time, :end_time, :availability)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table


  end
end

app/helpers/chairs_helper.rb
module ChairsHelper
end

app/helpers/derm_codes_helper.rb
module DermCodesHelper
end

app/helpers/officemenu_helper.rb
module OfficemenuHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/time_slots/_form.html.erb
<%= form_for(@time_slot) do |f| %>
  <% if @time_slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_slot.errors.count, "error") %> prohibited this time_slot from being saved:</h2>

      <ul>
      <% @time_slot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.text_field :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.text_field :end_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/time_slots/edit.html.erb
<h1>Editing time_slot</h1>

<%= render 'form' %>

<%= link_to 'Show', @time_slot %> |
<%= link_to 'Back', time_slots_path %>

app/views/time_slots/index.html.erb
<h1>Time Slots</h1>

<table>
  <thead>
    <tr>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @time_slots.each do |time_slot| %>
      <tr>
        <td><%= time_slot.start_time %></td>
        <td><%= time_slot.end_time %></td>
        <td><%= link_to 'Show', time_slot %></td>
        <td><%= link_to 'Edit', edit_time_slot_path(time_slot) %></td>
        <td><%= link_to 'Destroy', time_slot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Time slot', new_time_slot_path %>
<%= link_to 'Office Menu', officemenu_index_path %>

app/views/time_slots/new.html.erb
<h1>New time_slot</h1>

<%= render 'form' %>

<%= link_to 'Back', time_slots_path %>

app/views/time_slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @time_slot.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @time_slot.end_time %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @time_slot.availability %>
</p>

<%= link_to 'Edit', edit_time_slot_path(@time_slot) %> |
<%= link_to 'Back', time_slots_path %>