config/routes.rb
Rails.application.routes.draw do

  resources :statuses

  resources :chairs

  resources :time_slots

  resources :derm_codes

  get 'officemenu/index'

  get 'officemenu/show'

  get 'welcome/index'

  resources :appointments

  resources :physicians

  resources :patients

  resources :admin

  resources :officemenu

  resources :derm_codes

   root 'welcome#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  belongs_to :physician
  belongs_to :patient
  belongs_to :derm_code
  belongs_to :time_slot
  belongs_to :chair
  belongs_to :status
end

app/models/chair.rb
class Chair < ActiveRecord::Base

  has_many :appointments
  belongs_to :time_slot, through: :appointment

end

app/models/derm_code.rb
class DermCode < ActiveRecord::Base

  has_many :appointments
  has_many :physicians, :through => :appointments
end

app/models/invoicing_line_item.rb
class InvoicingLineItem < ActiveRecord::Base
  acts_as_line_item

  belongs_to :ledger_item, class_name: 'InvoicingLedgerItem'
end

app/models/invoicing_tax_rate.rb
class InvoicingTaxRate < ActiveRecord::Base
  acts_as_tax_rate
end

app/models/office.rb
class Office < ActiveRecord::Base


end

app/models/patient.rb
class Patient < ActiveRecord::Base

  has_many :appointments
  has_many :physicians, :through => :appointments
end

app/models/physician.rb
class Physician < ActiveRecord::Base

  has_many :appointments
  has_many :patients, :through => :appointments
end

app/models/status.rb
class Status < ActiveRecord::Base

  has_many :appointments
end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base

  has_many :appointments
  has_many :chairs, through: :appointments
  end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, only: [:show, :edit, :update, :destroy]

  # GET /physicians
  # GET /physicians.json
  def index
    @physicians = Physician.all
  end

  # GET /physicians/1
  # GET /physicians/1.json
  def show
  end

  # GET /physicians/new
  def new
    @physician = Physician.new
  end

  # GET /physicians/1/edit
  def edit
  end

  # POST /physicians
  # POST /physicians.json
  def create
    @physician = Physician.new(physician_params)

    respond_to do |format|
      if @physician.save
        format.html { redirect_to @physician, notice: 'Physician was successfully created.' }
        format.json { render :show, status: :created, location: @physician }
      else
        format.html { render :new }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physicians/1
  # PATCH/PUT /physicians/1.json
  def update
    respond_to do |format|
      if @physician.update(physician_params)
        format.html { redirect_to @physician, notice: 'Physician was successfully updated.' }
        format.json { render :show, status: :ok, location: @physician }
      else
        format.html { render :edit }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physicians/1
  # DELETE /physicians/1.json
  def destroy
    @physician.destroy
    respond_to do |format|
      format.html { redirect_to physicians_url, notice: 'Physician was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physician
      @physician = Physician.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def physician_params
      params.require(:physician).permit(:name)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table


  end
end

app/helpers/chairs_helper.rb
module ChairsHelper
end

app/helpers/derm_codes_helper.rb
module DermCodesHelper
end

app/helpers/officemenu_helper.rb
module OfficemenuHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/physicians/_form.html.erb
<%= form_for(@physician) do |f| %>
  <% if @physician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@physician.errors.count, "error") %> prohibited this physician from being saved:</h2>

      <ul>
      <% @physician.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/physicians/edit.html.erb
<h1>Editing physician</h1>

<%= render 'form' %>

<%= link_to 'Show', @physician %> |
<%= link_to 'Back', physicians_path %>

app/views/physicians/index.html.erb
<h1>Listing physicians</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @physicians.each do |physician| %>
      <tr>
        <td><%= physician.name %></td>
        <td><%= link_to 'Show', physician %></td>
        <td><%= link_to 'Edit', edit_physician_path(physician) %></td>
        <td><%= link_to 'Destroy', physician, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Physician', new_physician_path %>
<%= link_to 'New Appointment', new_appointment_path %>
<%= link_to 'Back', :back %>

app/views/physicians/new.html.erb
<h1>New physician</h1>

<%= render 'form' %>

<%= link_to 'Back', physicians_path %>

app/views/physicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @physician.name %>
</p>

<%= link_to 'Edit', edit_physician_path(@physician) %> |
<%= link_to 'Back', physicians_path %>