config/routes.rb
Rails.application.routes.draw do

  resources :statuses

  resources :chairs

  resources :time_slots

  resources :derm_codes

  get 'officemenu/index'

  get 'officemenu/show'

  get 'welcome/index'

  resources :appointments

  resources :physicians

  resources :patients

  resources :admin

  resources :officemenu

  resources :derm_codes

   root 'welcome#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  belongs_to :physician
  belongs_to :patient
  belongs_to :derm_code
  belongs_to :time_slot
  belongs_to :chair
  belongs_to :status
end

app/models/chair.rb
class Chair < ActiveRecord::Base

  has_many :appointments
  belongs_to :time_slot, through: :appointment

end

app/models/derm_code.rb
class DermCode < ActiveRecord::Base

  has_many :appointments
  has_many :physicians, :through => :appointments
end

app/models/invoicing_line_item.rb
class InvoicingLineItem < ActiveRecord::Base
  acts_as_line_item

  belongs_to :ledger_item, class_name: 'InvoicingLedgerItem'
end

app/models/invoicing_tax_rate.rb
class InvoicingTaxRate < ActiveRecord::Base
  acts_as_tax_rate
end

app/models/office.rb
class Office < ActiveRecord::Base


end

app/models/patient.rb
class Patient < ActiveRecord::Base

  has_many :appointments
  has_many :physicians, :through => :appointments
end

app/models/physician.rb
class Physician < ActiveRecord::Base

  has_many :appointments
  has_many :patients, :through => :appointments
end

app/models/status.rb
class Status < ActiveRecord::Base

  has_many :appointments
end

app/models/time_slot.rb
class TimeSlot < ActiveRecord::Base

  has_many :appointments
  has_many :chairs, through: :appointments
  end

app/controllers/derm_codes_controller.rb
class DermCodesController < ApplicationController
  before_action :set_derm_code, only: [:show, :edit, :update, :destroy]

  # GET /derm_codes
  # GET /derm_codes.json
  def index
    @derm_codes = DermCode.all
  end

  # GET /derm_codes/1
  # GET /derm_codes/1.json
  def show
  end

  # GET /derm_codes/new
  def new
    @derm_code = DermCode.new
  end

  # GET /derm_codes/1/edit
  def edit
  end

  # POST /derm_codes
  # POST /derm_codes.json
  def create
    @derm_code = DermCode.new(derm_code_params)

    respond_to do |format|
      if @derm_code.save
        format.html { redirect_to @derm_code, notice: 'Derm code was successfully created.' }
        format.json { render :show, status: :created, location: @derm_code }
      else
        format.html { render :new }
        format.json { render json: @derm_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /derm_codes/1
  # PATCH/PUT /derm_codes/1.json
  def update
    respond_to do |format|
      if @derm_code.update(derm_code_params)
        format.html { redirect_to @derm_code, notice: 'Derm code was successfully updated.' }
        format.json { render :show, status: :ok, location: @derm_code }
      else
        format.html { render :edit }
        format.json { render json: @derm_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /derm_codes/1
  # DELETE /derm_codes/1.json
  def destroy
    @derm_code.destroy
    respond_to do |format|
      format.html { redirect_to derm_codes_url, notice: 'Derm code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_derm_code
      @derm_code = DermCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def derm_code_params
      params.require(:derm_code).permit(:code, :description)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table


  end
end

app/helpers/chairs_helper.rb
module ChairsHelper
end

app/helpers/derm_codes_helper.rb
module DermCodesHelper
end

app/helpers/officemenu_helper.rb
module OfficemenuHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/derm_codes/_form.html.erb
<%= form_for(@derm_code) do |f| %>
  <% if @derm_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@derm_code.errors.count, "error") %> prohibited this derm_code from being saved:</h2>

      <ul>
      <% @derm_code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
    <div class="field">
      <%= f.label :amount %><br>
      <%= f.number :amount %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/derm_codes/edit.html.erb
<h1>Editing derm_code</h1>

<%= render 'form' %>

<%= link_to 'Show', @derm_code %> |
<%= link_to 'Back', derm_codes_path %>

app/views/derm_codes/index.html.erb
<h1>Listing Dermatology Codes</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Description</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @derm_codes.each do |derm_code| %>
      <tr>
        <td><%= derm_code.code %></td>
        <td><%= derm_code.description %></td>
        <td><%= derm_code.amount %></td>
        <td><%= link_to 'Show', derm_code %></td>
        <td><%= link_to 'Edit', edit_derm_code_path(derm_code) %></td>
        <td><%= link_to 'Destroy', derm_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Derm code', new_derm_code_path %>
<%= link_to 'Back' , :back %>

app/views/derm_codes/new.html.erb
<h1>New derm_code</h1>

<%= render 'form' %>

<%= link_to 'Back', derm_codes_path %>

app/views/derm_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @derm_code.code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @derm_code.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @derm_code.amount %>
</p>

<%= link_to 'Edit', edit_derm_code_path(@derm_code) %> |
<%= link_to 'Back', derm_codes_path %>